ARG OVERLAY_WS=/ws

FROM docker.io/osrf/ros:humble-desktop-full AS ros_build

ARG OVERLAY_WS
WORKDIR $OVERLAY_WS

COPY . .

{% for sysdep in system_dependencies %}
RUN apt-get update && apt-get install {{ sysdep }}
{% endfor %}

# TODO: Install all the build dependencies

RUN colcon build --packages-select {{ package_name }}

FROM ros:humble-ros-base

ARG OVERLAY_WS
WORKDIR $OVERLAY_WS

# source entrypoint setup
ENV OVERLAY_WS $OVERLAY_WS
RUN sed --in-place --expression \
  '$isource "$OVERLAY_WS/install/setup.bash"' \
  /ros_entrypoint.sh

{% for sysdep in system_dependencies %}
RUN apt-get update && apt-get install {{ sysdep }}
{% endfor %}

# TODO: Install the runtime dependencies

{% if launch_file %}
CMD [ "ros2", "launch", "{{ launch_file }}", {{ extra_args }} ]
{% elif command %}
CMD [ "ros2", "run", "{{ package_name }}", "{{ command_file }}", {{ extra_args }} ]
{% else %}
CMD [ "echo", "No execution option provided, container will not run!!" ]
{% endif %}
