apiVersion: coder.juancsu.flatboat/v0.6.0
kind: FlatboatWorkload
metadata:
  name: example-workload
spec:
  image: username/my_ros_pkg:latest
  launch_executable: example_launch.py
  args:
    - --rate
    - 50
    - -p
    - 3300
    - --robot
    - industrialarm
  runs-on: robot # or 'any' or 'cpu' or 'gpu'
