name = "jazzy_nvidia"
version = "1.3.0"

[artifacts]
workspace = "ghcr.io/JuanCSUCoder/flatboat-templates/robot_ws_jazzy_nvidia:1.3.0"
package = "ghcr.io/juancsucoder/flatboat-templates/robot_pkg_jazzy_nogpu:1.3.0"
workload = "ghcr.io/juancsucoder/flatboat-templates/robot_wl_jazzy:1.3.0"
bot = "https://juancsucoder.github.io/flatboat-docs#NotImplemented"
